server {
    listen 80;

    location /reparto/api/ {
        proxy_pass http://reparto-backend:3010/reparto/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /reparto/ {
        alias /usr/share/nginx/html/reparto/;
        try_files $uri $uri/ /reparto/index.html;
    }
}
